### ISSUE TITLE
Tried Demo but error said channel not found

### ISSUE THREAD

**Issue by stagfoo** [improvi/slack-chat#10]
Hi,
i tested the demo and it found all my channels but it couldn't send a message, the console said channel not found?

**Comment by arjunmat** [comment]
Hi stagfoo, can you share your slackChatOptions variable for debugging this?

**Comment by ghoshnirmalya** [comment]
@stagfoo Have a look at this comment https://github.com/improvi/slack-chat/issues/11#issuecomment-208352599. 

Once you've provided the **Slack API Token**, you can see all your channels by clicking on the **Click here to list your channels** link. Click on **use** to select any one of them. Double check that you're providing the correct API Token and the Channel ID. Once you're sure, click on **Try Now**.

Hope this helps!

**Comment by stagfoo** [comment]
I tried again and it didn't work but i changed the username to Testing and it started working, not sure if it was a time thing or not but after that it worked great!
