### ISSUE TITLE
Set it up?

### ISSUE THREAD

**Issue by greathappyforest** [improvi/slack-chat#11]
Hi, I was wondering, how to set it up in the correct way. 
Im filled out the slack infomation in the slack-chat.js. 
And include the slack-chat.js in my page.And call $(<elem>).slackChat(slackChatOptions); 

It doesnt show anything..Do I set up in the wrong way?? 
Anyone give me some detail for setting it up?

**Comment by arjunmat** [comment]
Hi lyl1988, can you share the slackChatOptions variable? tough to debug without it.

Also, check the console for any errors logged.

**Comment by ghoshnirmalya** [comment]
@lyl1988 I've tried the demo app and it works fine. If you go to the **index.html** file and fill out the details, it should work fine.

Try testing with a test token which you can generate [here](https://api.slack.com/docs/oauth-test-tokens). After you fill up all the details, the icon below will be shown on the bottom right of your page.

![screen shot 2016-04-11 at 7 17 05 pm](https://cloud.githubusercontent.com/assets/6391763/14429210/1cdfc88e-001a-11e6-902e-a3f3392e178d.png)

You can click on it to proceed.

As for your case, you can check if there're any errors logged in your console as @improvi mentioned.

Hope this helps.
