### ISSUE TITLE
Name of automatic created channel (private) has no numbers

### ISSUE THREAD

**Issue by ulisesguerrero** [improvi/slack-chat#21]
As far as I've read the code, the new auto-created channels are supposed to have a random number. But currently, the channels created have no numbers, they only add "name"+"test-user". This makes it very likely for a user to repeat and see someone else's chat.

**Comment by arjunmat** [comment]
In the slackChatOptions, if no userId is specified, the random number will be used.

**Comment by ulisesguerrero** [comment]
Ok. The demo webform should also be changed, so that it will allow running the chat without UserID. Currently it says required, and won't start the chat without userid.
