### ISSUE TITLE
error: channel_not_found

### ISSUE THREAD

**Issue by shaneheyworth** [improvi/slack-chat#3]
I've got this integrated as per the downloadable content and your instructions. My app successfully sends messages but every 2 seconds I get told that the channel isn't found, and none of my messages are loading

**I deleted the API key for screenshot purposes**

<img width="1036" alt="screen shot 2016-02-08 at 7 54 04 pm" src="https://cloud.githubusercontent.com/assets/16281266/12904474/c2a3817e-ce9d-11e5-8f40-0874e27a5e9e.png">
<img width="1031" alt="screen shot 2016-02-08 at 7 54 16 pm" src="https://cloud.githubusercontent.com/assets/16281266/12904475/c2b5ed5a-ce9d-11e5-8f8a-be5ecff6e95a.png">

**Comment by arjunmat** [comment]
@shaneheyworth - the channel ID will be a number similar to C0AJ5A082. You can find your channel ids from this page: http://slack-chat.improvi.in.

Since this is not an issue, closing this.
