### ISSUE TITLE
Create new channel or skip channels

### ISSUE THREAD

**Issue by RealJordan** [improvi/slack-chat#7]
Hi there, 
There's a potential that we will have multiple people trying to contact us at the same time, which would mean that them only using the same channel could be an issue. 

So it would be an idea to be able to create a unique channel for a new user (e.g. based on the name they put in, and date, e.g. "16032016-john-smith" as a channel name.

Or, if this isn't possible, make it so that you can have 10 (for example) potential slack channels for live chat, and if channel 1 has had an update within the last 10 minutes, then channel 2 will get tried, and if that has been updated in the last 10 minutes, channel 3 tried, until channel 10.

**Comment by arjunmat** [comment]
@RealJordan - you can use the private channel feature of SlackChat for this.
